services:
  mongo:
    image: mongo:6
    container_name: hospital-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: "./new backend final/backends"
      dockerfile: Dockerfile
    container_name: hospital-backend
    restart: always
    env_file:
      - "./new backend final/backends/config/config.env"
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      PORT: 5000
      FRONTEND_URL: "http://localhost:3000"
      DASHBOARD_URL: "http://localhost:3001"
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: "./new frontend final/frontends"
      dockerfile: Dockerfile
    container_name: hospital-frontend
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: "http://localhost:5000"
    ports:
      - "3000:80"

  dashboard:
    build:
      context: "./new dashboard final/dashboard"
      dockerfile: Dockerfile
    container_name: hospital-dashboard
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: "http://localhost:5000"   # axios.js will append /api/v1
    ports:
      - "3001:80"

volumes:
  mongo-data: