apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-frontend
  template:
    metadata:
      labels:
        app: hospital-frontend
    spec:
      containers:
        - name: hospital-frontend
          image: docker.io/shahaly/hospital-mern-stack-frontend:github-sha-0c05f46d98e94e2c635772f8368bc19192260dda
          imagePullPolicy: Always # Never
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://hospital-backend-service:5000"
