apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - dashboard-deployment.yaml
  - dashboard-service.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - mongodb-exporter.yaml
  - ingress-deployment.yaml
  - ingress-service.yaml
