apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: bitnami/mongodb-exporter:latest
          args:
            - '--mongodb.uri=mongodb://mongo-service:27017/MERN_STACK_HOSPITAL_MANAGMENT_SYSTEM'
          ports:
            - name: metrics
              containerPort: 9216

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter-service
  labels:
    app: mongodb-exporter
spec:
  type: NodePort
  selector:
    app: mongodb-exporter
  ports:
    - name: http-metrics
      port: 9216        # service port inside cluster
      targetPort: 9216  # containerPort
      nodePort: 30290   # NodePort exposed on all k8s nodes
