apiVersion: v2
name: clinic-appointment-system
description: A Helm chart for the Clinic Appointment System
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: dashboard
    version: 0.1.0
    repository: "file://charts/dashboard"
  - name: mongo
    version: 0.1.0
    repository: "file://charts/mongo"
