name: CI - Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  DOCKER_ORG: moatazkamalmohamed
  BASE_NAME: hospital-mern-stack

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # =========================
      # Backend Image
      # =========================
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: "./new backend final/backends"
          file: "./new backend final/backends/Dockerfile"
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.DOCKER_ORG }}/${{ env.BASE_NAME }}-backend:latest
            ${{ env.REGISTRY }}/${{ env.DOCKER_ORG }}/${{ env.BASE_NAME }}-backend:github-sha-${{ github.sha }}

      # =========================
      # Frontend Image
      # =========================
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: "./new frontend final/frontends"
          file: "./new frontend final/frontends/Dockerfile"
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.DOCKER_ORG }}/${{ env.BASE_NAME }}-frontend:latest
            ${{ env.REGISTRY }}/${{ env.DOCKER_ORG }}/${{ env.BASE_NAME }}-frontend:github-sha-${{ github.sha }}

      # =========================
      # Dashboard Image
      # =========================
      - name: Build and push dashboard image
        uses: docker/build-push-action@v6
        with:
          context: "./new dashboard final/dashboard"
          file: "./new dashboard final/dashboard/Dockerfile"
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.DOCKER_ORG }}/${{ env.BASE_NAME }}-dashboard:latest
            ${{ env.REGISTRY }}/${{ env.DOCKER_ORG }}/${{ env.BASE_NAME }}-dashboard:github-sha-${{ github.sha }}
